name: Node.js Docker Build and Deploy

on:
  push:
    branches:
      - master # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t your-docker-image-name:latest .
      working-directory: ${{ github.workspace }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ ishackdeen }}
        password: ${{ Ideen1865@ }}

    - name: Push Docker image to Docker Hub
      run: docker push your-docker-image-name:latest

    - name: Deploy to Virtual Machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker pull your-docker-image-name:latest
          docker run -d --name your-container-name -p 8080:80 your-docker-image-name:latest
