name: CI/CD with Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t your-image-name .

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag your-image-name ${{ secrets.DOCKERHUB_USERNAME }}/ishackdeen/node_task:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ishackdeen/node_task:latest
